### ISSUE TITLE
v1.0.0 on npm missing built files

### ISSUE THREAD

**Issue by qkevinto** [ramasilveyra/mjml-loader#7]
Is it just me or is the latest published version on npm missing the built files?

`package.json` indicates `main: build/index.js`, however it's not present after doing an npm install.

**Comment by ramasilveyra** [comment]
@qkevinto @PhilWaldmann Upps, sorry. Can you try again? I just released v1.0.1

**Comment by PhilWaldmann** [comment]
Works! 👍
